### ISSUE TITLE
Recovery Bootloop

### ISSUE THREAD

**Issue by PhoenixPeca** [mohancm/android_device_lenovo_A7010a48#24]
Resetting the device to factory in settings renders the device in bootloop to the recovery. It can't proceed to the system no matter how I tried.

**Comment by PhoenixPeca** [comment]
If you do a factory reset within android settings in Nougat, the phone will go into TWRP boot loop and stay like this even when cleared.

**Comment by mohancm** [comment]
@PhoenixPeca check the instruction on xda forums properly.
there are two seperate recoveries based on nougat and Marshmallow.
do check it again

**Comment by PhoenixPeca** [comment]
@mohancm unfortunately it still does not work. I have followed the instructions in the xda forums carefully and properly. Everything seems to work fine except the "factory reset" option in the android settings on the LOS Nougat, DOT Nougat, & RR nougat OSes. You should try this yourself in your device. Doing it causes the device to boot directly into the TWRP recovery on all succeeding boots.

I have now reinstalled the stock ROM, because of this bug. I hope we can find a solution on this. The Nougat ROM is indeed very awesome.
